modLoader="javafml"
loaderVersion="[${javafml_min},${javafml_max})"
license="MIT"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_title}"
    authors="${mod_author}"
    description='''
Client side mod adding local time to chat and sending message about in-game day and moon phases.
    '''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version_min},${forge_version_max})"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version_min},${minecraft_version_max})"
    ordering="NONE"
    side="CLIENT"

